server:
  port: 18060
  host: localhost
erp:
  ip: 54.254.54.116
  port: 8001
  username: APIUSER
  password: acmeinter123
  authUrl: https://${erp.ip}:${erp.port}/EN/001.1/login
  addressUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Common/DeliveryAddresses
  customerOrderUrl: https://${erp.ip}:${erp.port}/EN/001.1/api/v1/Sales/CustomerOrders
  customerUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Sales/Customers
  departmentUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Common/Departments
  invoiceLogUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Sales/InvoiceLogs
  partUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Inventory/Parts
  personUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Common/Persons
  vatRateUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Common/VatRates
  vatGroupUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Common/VatGroups
  supplierUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Purchase/Suppliers
  purchaseOrderUrl: https://${erp.ip}:${erp.port}/sv/001.1/api/v1/Purchase/PurchaseOrders
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${server.host}:5432/sales
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  data:
    elasticsearch:
      cluster-name: saleService
      cluster-nodes: ${server.host}:9200
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: web-support@acme-inter.com
    password: ncqwidokjouqvxgx
    port: 587
    smtp:
      auth: true
      starttls:
        enable: true
    protocol: smtp
    debug: false
    test-connection: false  
app:
  web:
    site: http://localhost:4200/
  mail:
    sender: IDENMATIC
    support:
      email: web-support@acme-inter.com
    templates:
      location: /templates/
  jwt:
    secret: AGEAYwBtAGUAfgBpAG4AdABlAHIAQABpAGQAZQBuAG0AYQB0AGkAYw==
    expireMs: 3600000
    refreshExpirationMs: 3600000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2000KB
      max-file-size: 10MB
      max-request-size: 10MB
      location: ./uploads  
file:
  upload-dir: ./uploads
aes:
  secreteKey: kkL1GLd8NFajZtdeLh87DvA7SAXXvtLb
