server:
  port: 18060
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sales
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: web-support@acme-inter.com
    password: ncqwidokjouqvxgx
    port: 587
    smtp:
      auth: true
      starttls:
        enable: true
    protocol: smtp
    debug: false
    test-connection: false  
app:
  web:
    site: http://localhost:4200/
  mail:
    sender: IDENMATIC
    support:
      email: web-support@acme-inter.com
    templates:
      location: /templates/
  jwt:
    secret: AGEAYwBtAGUAfgBpAG4AdABlAHIAQABpAGQAZQBuAG0AYQB0AGkAYw==
    expireMs: 3600000
    refreshExpirationMs: 3600000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2000KB
      max-file-size: 10MB
      max-request-size: 10MB
      location: ./uploads  
file:
  upload-dir: ./uploads
aes:
  secreteKey: kkL1GLd8NFajZtdeLh87DvA7SAXXvtLb
